name: build
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Grant execute permission
        run: chmod +x gradlew || true
      - name: Build
        run: ./gradlew --refresh-dependencies clean build
      - uses: actions/upload-artifact@v4
        with:
          name: flying-pigs-esp
          path: build/libs/*.jar
